Fixes warnings emitted by clang compiler.
Clang emited few warnings during build, so this commit fixes them.
```
bits/stub.cpp:151:9: error:
     warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
            delete this->buf;
            ^
                  []
    |
151 |         delete this->buf;
```

```
cbits/stub.cpp:471:1: error:
     warning: control may reach end of non-void function [-Wreturn-type]
    |
471 | }
    | ^
}
```